# This workflow will build and deploy a Python app to an Azure Web App when a push is made to the main branch.

name: Build and deploy Python app to Azure Web App - climopilot-api

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r backend/requirements.txt

    - name: Test with pytest
      run: |
        source venv/bin/activate
        python -m pytest backend/tests/ -v

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r backend/requirements.txt

    - name: Download artifact from build job
      uses: actions/download-artifact@v3

    - name: Unzip artifact from build job
      run: unzip -o backend.zip -d backend

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'climopilot-api'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1234567890ABCDEF1234567890ABCDEF }}
        package: backend
